openapi: 3.0.0
info:
  title: FRED API
  description: API for accessing economic data from the Federal Reserve Economic Data (FRED) database.
  version: 1.0.1
servers:
  - url: https://api.stlouisfed.org/fred
    description: FRED API server
paths:
  /category:
    get:
      operationId: getCategory
      summary: Get a category.
      parameters:
        - name: api_key
          description: you_api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          schema:
            type: integer
            default: 0
      responses:
        "200":
          description: Successful response
  /category/children:
    get:
      operationId: getCategoryChildren
      summary: Get the child categories for a specified parent category.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          schema:
            type: integer
            default: 0
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Successful response
  /category/related:
    get:
      operationId: getCategoryRelated
      summary: Get related categories for a specified category.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          schema:
            type: integer
            default: 0
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Successful response with related categories
  /category/series:
    get:
      operationId: getCategorySeries
      summary: Retrieve series within a specified category.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          required: true
          schema:
            type: integer
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: Maximum number of results to return
        - name: offset
          in: query
          schema:
            type: integer
            description: Offset for the start of the results
        - name: order_by
          in: query
          schema:
            type: string
            enum:
              - series_id
              - title
              - units
              - frequency
              - seasonal_adjustment
              - realtime_start
              - realtime_end
              - last_updated
              - observation_start
              - observation_end
              - popularity
              - group_popularity
        - name: sort_order
          in: query
          schema:
            type: string
            enum:
              - asc
              - desc
        - name: filter_variable
          in: query
          schema:
            type: string
        - name: filter_value
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Successful response with series data
  /category/tags:
    get:
      operationId: getCategoryTags
      summary: Retrieve tags for a specific category.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          required: true
          schema:
            type: integer
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: Maximum number of results to return
        - name: offset
          in: query
          schema:
            type: integer
            description: Offset for the start of the results
        - name: order_by
          in: query
          schema:
            type: string
            enum:
              - name
              - group_id
        - name: sort_order
          in: query
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        "200":
          description: Successful response with category tags
  /category/related_tags:
    get:
      operationId: getCategoryRelatedTags
      summary: Retrieve related tags for a specific category.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum:
              - xml
              - json
            default: xml
        - name: category_id
          in: query
          required: true
          schema:
            type: integer
        - name: tag_names
          in: query
          required: true
          schema:
            type: string
            description: Names of tags to find related tags for
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: Maximum number of results to return
        - name: offset
          in: query
          schema:
            type: integer
            description: Offset for the start of the results
        - name: order_by
          in: query
          schema:
            type: string
            enum:
              - series_count
              - popularity
        - name: sort_order
          in: query
          schema:
            type: string
            enum:
              - asc
              - desc
      responses:
        "200":
          description: Successful response with related tags

  /releases:
    get:
      operationId: getReleases
      summary: Get all releases of economic data.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: The maximum number of results to return
        - name: offset
          in: query
          schema:
            type: integer
            description: The offset for the start of results
        - name: order_by
          in: query
          schema:
            type: string
            enum: [release_id, name, press_release, realtime_start, realtime_end]
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
        - name: filter_variable
          in: query
          schema:
            type: string
        - name: filter_value
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A list of all economic data releases
  /releases/dates:
    get:
      operationId: getReleaseDates
      summary: Retrieve release dates for all economic data.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: The maximum number of results to return
        - name: offset
          in: query
          schema:
            type: integer
            description: The offset for the start of results
        - name: last_updated
          in: query
          schema:
            type: string
            format: date-time
            description: Only include releases that have been updated since this time.
      responses:
        '200':
          description: A list of release dates for economic data
  /release:
    get:
      operationId: getReleaseInfo
      summary: Get information for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID for the release of interest.
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Detailed information about the specified release
  /release/dates:
    get:
      operationId: getReleaseDates
      summary: Retrieve release dates for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release whose dates are being queried.
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Release dates for the specified economic data release
  /release/series:
    get:
      operationId: getReleaseSeries
      summary: Get series for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release whose series are being queried.
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: The maximum number of results to return.
        - name: offset
          in: query
          schema:
            type: integer
            description: The offset for the start of results.
        - name: order_by
          in: query
          schema:
            type: string
            enum: [series_id, title, units, frequency, seasonal_adjustment, realtime_start, realtime_end, last_updated, observation_start, observation_end, popularity, group_popularity]
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
        - name: filter_variable
          in: query
          schema:
            type: string
        - name: filter_value
          in: query
          schema:
            type: string
      responses:
        '200':
          description: A list of related tags for the specified economic data release
  /release/sources:
    get:
      operationId: getReleaseSources
      summary: Get sources for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release whose sources are being queried.
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A list of sources for the specified economic data release
  /release/tags:
    get:
      operationId: getReleaseTags
      summary: Get tags for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release whose tags are being queried.
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: The maximum number of results to return.
        - name: offset
          in: query
          schema:
            type: integer
            description: The offset for the start of results.
        - name: order_by
          in: query
          schema:
            type: string
            enum: [name, group_id]
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
        - name: search_text
          in: query
          schema:
            type: string
            description: A keyword or phrase to search for within the tag names.
      responses:
        '200':
          description: A list of tags for the specified economic data release
  /release/related_tags:
    get:
      operationId: getReleaseRelatedTags
      summary: Retrieve related tags for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release for which related tags are being queried.
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: tag_names
          in: query
          required: true
          schema:
            type: string
            description: Names of tags to find related tags for.
        - name: realtime_start
          in: query
          schema:
            type: string
            format: date
        - name: realtime_end
          in: query
          schema:
            type: string
            format: date
        - name: limit
          in: query
          schema:
            type: integer
            description: The maximum number of results to return.
        - name: offset
          in: query
          schema:
            type: integer
            description: The offset for the start of results.
        - name: order_by
          in: query
          schema:
            type: string
            enum: [series_count, popularity]
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: A list of related tags for the specified economic data release
  /release/tables:
    get:
      operationId: getReleaseTables
      summary: Get data tables for a specific economic data release.
      parameters:
        - name: api_key
          in: query
          required: true
          schema:
            type: string
        - name: release_id
          in: query
          required: true
          schema:
            type: integer
            description: The unique ID of the release for which tables are being queried.
        - name: file_type
          in: query
          schema:
            type: string
            enum: [xml, json]
            default: json
        - name: element_id
          in: query
          schema:
            type: integer
            description: The unique ID of the element for which tables are being queried.
        - name: include_observations
          in: query
          schema:
            type: boolean
            description: Boolean to include observations in the table.
        - name: observation_date
          in: query
          schema:
            type: string
            format: date
            description: The date of the observation to include in the table.
      responses:
        '200':
          description: Data tables for the specified economic data release
